# NetOffice project build definition
version: 2.0.0.{build}

branches:
  only:
    - master
    - /dev.*/
  except:
    - gh-pages
    - import/*


image: Visual Studio 2017

platform: Any CPU
configuration:
  - Debug
  - Release

environment:
  VisualStudioVersion: 15.0

init:
  git config --global core.autocrlf true

build_script:
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild.exe Source\NetOffice.sln /Target:Build;Pack /Verbosity:normal /logger:%MSBuildLogger%

before_build:
  - appveyor-retry nuget restore Source\NetOffice.sln

artifacts:
  - path: 'Source\**\bin\%CONFIGURATION%\*.nupkg'
    name: NetOffice Packages
